language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script: composer install

script: phpunit ./tests/CorsMiddlewareTest.php

after_success:
  - bash <(curl -s https://codecov.io/bash)