language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script: composer install

script: phpunit ./tests --colors=never  --configuration phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
