language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

allow_failures:
  - php: 7.0
  - php: 7.1

before_script: composer install

script: phpunit ./tests --colors=never

after_success:
  - bash <(curl -s https://codecov.io/bash)